name: Build and Deploy to GHCR

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y aria2 cmake make

    - name: Install LLVM
      run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
    
    - name: Set up Android NDK r27c
      run: |
        aria2c -o android-ndk-r27c-linux.zip https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
        unzip -q -d ~ android-ndk-r27c-linux.zip
    
    - name: Build Project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Wrapper.x86_64.${{ env.sha_short }}
        path: |
          rootfs
          wrapper
          Dockerfile

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry (GHCR)
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and Push Docker Image to GHCR
      run: |
        IMAGE_NAME="ghcr.io/genzpn/wrapper"
        
        docker build -t ${IMAGE_NAME}:${{ env.sha_short }} .
        docker tag ${IMAGE_NAME}:${{ env.sha_short }} ${IMAGE_NAME}:latest

        docker push ${IMAGE_NAME}:${{ env.sha_short }}
        docker push ${IMAGE_NAME}:latest
